image:
  repository: jellyfin/jellyfin
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 8096
  nodePort: 30096

persistence:
  config:
    enabled: false
    size: 1Gi
  media:
    enabled: false
    size: 10Gi
  cache:
    enabled: false
    size: 1Gi

