apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki
  namespace: jellyfin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      labels:
        app: loki
    spec:
      securityContext:
        fsGroup: 10001
        runAsGroup: 10001
        runAsNonRoot: true
        runAsUser: 10001
      initContainers:
        - name: init-loki
          image: busybox:1.35
          command:
            - sh
            - -c
            - |
              mkdir -p /loki/chunks /loki/rules
              chown -R 10001:10001 /loki
          volumeMounts:
            - name: loki-storage
              mountPath: /loki
          securityContext:
            runAsUser: 0
      containers:
        - name: loki
          image: grafana/loki:latest
          args:
            - "-config.file=/etc/loki/loki-config.yml"
          ports:
            - containerPort: 3100
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 10001
          volumeMounts:
            - name: loki-config
              mountPath: /etc/loki
            - name: loki-storage
              mountPath: /loki
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: loki-config
          configMap:
            name: loki-config
        - name: loki-storage
          persistentVolumeClaim:
            claimName: loki-pvc
        - name: tmp
          emptyDir: {}