apiVersion: v1
kind: ConfigMap
metadata:
  name: caddy-config
  namespace: jellyfin
data:
  Caddyfile: |
    {
      email chhilifanas@gmail.com
    }
    
    jellyfin.chhilif.com {
      reverse_proxy jellyfin:8096
      encode gzip
      
      header {
        X-Forwarded-Proto {scheme}
        X-Forwarded-For {remote_host}
        X-Real-IP {remote_host}
      }
    }
    
    devapi.budgeteer.chhilif.com {
      reverse_proxy budgeteer:8080
      encode gzip
    }
    
    grafana.budgeteer.chhilif.com {
      reverse_proxy prometheus-stack-grafana:80
      encode gzip
      
      header {
        X-Forwarded-Proto {scheme}
        X-Forwarded-For {remote_host}
        X-Real-IP {remote_host}
      }
    }
    
    loki.chhilif.com {
      reverse_proxy loki:3100
      encode gzip
    }
    
    prometheus.chhilif.com {
      reverse_proxy prometheus-stack-kube-prom-prometheus:9090
      encode gzip
    }
    
    alertmanager.chhilif.com {
      reverse_proxy prometheus-stack-kube-prom-alertmanager:9093
      encode gzip
    }
    
    127.0.0.1:80, [::1]:80 {
      respond "Please use domain names to access services"
    }
    
    chhilif.com {
      redir https://jellyfin.chhilif.com{uri}
    }