apiVersion: v1
kind: ConfigMap
metadata:
  name: caddy-config
  namespace: jellyfin
data:
  Caddyfile: |
    127.0.0.1:80, [::1]:80 {
      reverse_proxy jellyfin.jellyfin.svc.cluster.local:8096
    }