apiVersion: v1
kind: Service
metadata:
  name: jellyfin
  namespace: jellyfin
spec:
  type: NodePort
  ports:
  - port: 8096
    targetPort: 8096
    nodePort: 30096
  selector:
    app: jellyfin
---
# Additional ClusterIP service for direct port mapping
apiVersion: v1
kind: Service
metadata:
  name: jellyfin-direct
  namespace: jellyfin
spec:
  type: ClusterIP
  ports:
  - port: 8096
    targetPort: 8096
  selector:
    app: jellyfin
