apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./jellyfin-cluster/infrastructure/
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system