apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-config
  namespace: flux-system
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: "./jellyfin-cluster/infrastructure/metallb-config"
  prune: true
  wait: true
  timeout: 5m
  dependsOn:
    - name: infrastructure
  healthChecks:
    - apiVersion: v1
      kind: Deployment
      name: metallb-controller
      namespace: metallb-system