apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-stack-values
  namespace: jellyfin
data:
  values.yaml: |
    prometheus:
      enabled: true
      prometheusSpec:
        scrapeInterval: 15s
        evaluationInterval: 15s
        retention: 7d
        
        storageSpec:
          volumeClaimTemplate:
            spec:
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 25Gi
        
        resources:
          requests:
            memory: 2Gi
            cpu: 500m
          limits:
            memory: 4Gi
            cpu: 1000m
        
        additionalScrapeConfigs:
          - job_name: 'prometheus'
            static_configs:
              - targets: ['localhost:9090']
          
          - job_name: 'node_exporter'
            static_configs:
              - targets: ['prometheus-stack-prometheus-node-exporter.jellyfin.svc.cluster.local:9100']
            honor_labels: true
            metric_relabel_configs:
              - source_labels: [__address__]
                regex: (.*)
                target_label: instance
                replacement: host_machine
          
          - job_name: 'spring-boot-application'
            metrics_path: '/actuator/prometheus'
            scrape_interval: 15s
            static_configs:
              - targets: ['budgeteer.jellyfin.svc.cluster.local:8080']

    prometheus-node-exporter:
      enabled: true
      tolerations:
        - effect: NoSchedule
          operator: Exists
        - effect: NoExecute
          operator: Exists

    grafana:
      enabled: true
      adminUser: admin
      adminPassword: "admin"
      persistence:
        enabled: true
        size: 10Gi
      ingress:
        enabled: true
        hosts:
          - grafana.budgeteer.chhilif.com
        annotations:
          kubernetes.io/ingress.class: nginx
          cert-manager.io/cluster-issuer: letsencrypt-prod
        tls:
          - secretName: grafana-tls
            hosts:
              - grafana.budgeteer.chhilif.com

    alertmanager:
      enabled: true
      alertmanagerSpec:
        resources:
          requests:
            memory: 256Mi
            cpu: 100m
          limits:
            memory: 512Mi
            cpu: 200m

    kube-state-metrics:
      enabled: true