apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus-stack
  namespace: jellyfin
spec:
  interval: 5m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: 73.2.0
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
      interval: 10m
  valuesFrom:
  - kind: ConfigMap
    name: prometheus-stack-values