apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  interval: 5m
  chart:
    spec:
      chart: ingress-nginx
      version: '4.8.3'
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: ingress-nginx
  values:
    controller:
      service:
        type: LoadBalancer
        # This will get an IP from your MetalLB pool
      config:
        # Optional: Add any nginx config you need
        use-real-ip: "true"
        real-ip-header: "X-Forwarded-For"